# Generated by Django 4.2 on 2023-05-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id',
            new_name='id_c',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='id',
            new_name='id_l',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='id_p',
        ),
    ]
