# Generated by Django 4.2 on 2023-05-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_rename_id_comment_id_c_rename_id_like_id_l_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_c',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id_p',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id_l',
        ),
        migrations.AddField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
