# Generated by Django 4.2 on 2023-05-04 17:04

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_rename_id_c_comment_id_rename_id_p_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=social.models.image_save_path),
        ),
    ]
