# Generated by Django 4.2 on 2023-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='no_of_followers',
            field=models.IntegerField(default=0),
        ),
    ]
